# Generated by Django 4.2.7 on 2023-12-29 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userprofile_city_alter_userprofile_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
