# Generated by Django 4.2.7 on 2024-01-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productgallary_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallary',
            options={'verbose_name_plural': 'productgallary'},
        ),
    ]
