# Generated by Django 4.2.7 on 2023-12-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
