# Generated by Django 3.1 on 2023-12-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mart', '0005_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
